### ISSUE TITLE
updated table of contents for the document

### ISSUE THREAD

**Issue by mariojmdavid** [eosc-sq/ensure-sq#29]
* 1 - Introduction
* 2 - Definition of quality
  * 2.1 - Software Quality models: Survey
  * 2.2 - Software Quality characteristics
  * 2.3 - Software Quality attributes (currently are)
    * 2.3.1 - Attribute type: Metrics on Source Code
    * 2.3.2 - Attribute type: Metrics Time
    * 2.3.3 - Attribute type: Qualitative
    * 2.3.4 - Attribute type: DevOps/Automation
* 3 - Landscaping/Recommendations
  * 3.1 - Types and categories of Research SW
  * 3.2 - Definition and references of Research SW
  * 3.3 - Quality Attributes recommendations (Per user story type - c.f. SG1 document, we may/should change the subsection title)
    * 3.3.1 - Individual researcher creating software for personal use (e.g. a PhD student)
    * 3.3.2 - A research team creating an application or workflow for use within the team
    * 3.3.3 - A team / community developing open source software
    * 3.3.4 - A team or community creating a service, a platform or an infrastructure
    * 3.3.5 - A team / community developing software in an industrial context
  * 3.4 - Example of tools, services and infrastructures to implement Quality Assurance for RS
* 4 - Perspectives
  * 4.1 - Developer
  * 4.2 - User
  * 4.3 - Resource/Service provider
* 5 - Software in production
  * 5.1 - Quality Attributes related to SW release management
  * 5.2 - Quality Attributes related to SW and services in production
* 6 - Metadata for software
  * 6.1 - Metadata schema for SW (Codemeta, other(s)...)
  * 6.2 - The case for FAIR for Research Software (FAIR4RS)
  * 6.3 - Quality Attributes and the FAIR4RS principles
* 7 - Summary and conclusions
* Bibliography

**Comment by cerlane** [comment]
For Section 3.3.4, I would suggest to add infrastructure to include infrastructure as code use cases.

**Comment by mariojmdavid** [comment]
@cerlane agree and added in the original issue description

**Comment by louvetv** [comment]
Fine for me too, thanks !

**Comment by MaximeVdB** [comment]
Thanks Mario for the proposal. One thing that comes to mind regarding (3):

Would it make more sense to split this section up into "Landscaping" and "Recommendations" sections?

And if you consider the current subsections 3.1 and 3.2 to be "landscaping" activities, it could be considered to move them earlier in the document.

So something like this:
```
1 - Introduction
2 - Landscaping
    2.1 - Types and categories of Research SW
    2.2 - Definition and references of Research SW
3 - Definition of quality
    3.1 - Software Quality models: Survey
    3.2 - Software Quality characteristics
    3.3 - Software Quality attributes (currently are)
        3.3.1 - Attribute type: Metrics on Source Code
        3.3.2 - Attribute type: Metrics Time
        3.3.3 - Attribute type: Qualitative
        3.3.4 - Attribute type: DevOps/Automation
4 - Recommendations
    4.1 - Quality Attributes recommendations (Per user story type - c.f. SG1 document, we may/should change the subsection title)
        4.3.1 - Individual researcher creating software for personal use (e.g. a PhD student)
        4.3.2 - A research team creating an application or workflow for use within the team
        4.3.3 - A team / community developing open source software
        4.3.4 - A team or community creating a service, a platform or an infrastructure
        4.3.5 - A team / community developing software in an industrial context
    4.2 - Example of tools, services and infrastructures to implement Quality Assurance for RS

etc.
```
Again, just an idea. Perhaps we should first agree here on what we understand with the term "landscaping" in this context? To my knowledge, this is not a commonly used term (at least outside EOSC).

**Comment by dgarijo** [comment]
I actually like the structure proposeb by @MaximeVdB. It flows better.

**Comment by mariojmdavid** [comment]
I also agree, with a slight thing, only 3.1 in @MaximeVdB change to 2.3 (in Landscaping) and keeping 3.2 in section 3, I will create the new ToC below

**Comment by mcolom** [comment]
Looks great to me, thanks Mario!

**Comment by massimotorquati** [comment]
Looks good to me too. Thanks.

**Comment by mariojmdavid** [comment]
on behalf of Violaine:

"I would put 2.2 after 3 and 2.3 in the 3rd part no ?
Then 4 will naturally follow 2 and 3 as all the definitions will be then set.
In 4 I think that a diagram can make the text more explicit."

The current ToC is the following, please propose what changes you would make in a separate comment.

```
1 - Introduction
        Editing: Mario David
        Contributors:
2 - Landscaping
        Editing: Violaine Louvet
        Contributors: Elisabetta Ronchieri
    2.1 - Research Software stack and types
    2.2 - Definition and references of Research SW
    2.3 - Software Quality models: Survey
3 - Definition of quality
        Editing: Mario David, Daniel Garijo
        Contributors: Miguel Colom, Elisabetta Ronchieri
    3.1 - Software Quality characteristics
    3.2 - Software Quality attributes
4 - Recommendations
        Editing: Violaine Louvet
        Contributors: Elisabetta Ronchieri
    4.1 - Quality Attributes recommendations
        4.1.1 - Individual researcher creating software for personal use (e.g. a PhD student)
        4.1.2 - A research team creating an application or workflow for use within the team
        4.1.3 - A team / community developing open source software
        4.1.4 - A team or community creating a service, a platform or an infrastructure
        4.1.5 - A team / community developing software in an industrial context
    4.2 - Example of tools, services and infrastructures to implement Quality Assurance for RS
5 - Perspectives
        Editing: Miguel Colom
        Contributors: Massimo Torquati
    5.1 - Developer
    5.2 - User
    5.3 - Resource/Service provider
6 - Software in production
        Editing: Miguel Colom
        Contributors: Cerlane Leong
    6.1 - Quality Attributes related to SW release management
    6.2 - Quality Attributes related to SW and services in production
7 - Metadata for software
        Editing: Daniel Garijo
        Contributors: Leyla Jael Castro
    7.1 - Metadata schema for SW
    7.2 - The case for FAIR for Research Software (FAIR4RS)
    7.3 - Quality Attributes and the FAIR4RS principles
8 - Summary and conclusions
        Editing: Mario David
        Contributors:
Appendix - Quality Attributes
References
```

**Comment by louvetv** [comment]
New proposition with 2.2 after 3 and 2.3 in the 3rd :

1 - Introduction

2 - Definition of quality
    2.1 - Software Quality characteristics
    2.2 - Software Quality attributes
    2.3 - Software Quality models: Survey

3 - Landscaping
    3.1 - Research Software stack and types. Links to Software Quality characteristics
    3.2 - Definition and references of Research SW. 

4 - Recommendations
    4.1 - Quality Attributes recommendations
        4.1.1 - Individual researcher creating software for personal use (e.g. a PhD student)
        4.1.2 - A research team creating an application or workflow for use within the team
        4.1.3 - A team / community developing open source software
        4.1.4 - A team or community creating a service, a platform or an infrastructure
        4.1.5 - A team / community developing software in an industrial context
    4.2 - Example of tools, services and infrastructures to implement Quality Assurance for RS

5 - Perspectives
    5.1 - Developer
    5.2 - User
    5.3 - Resource/Service provider

6 - Software in production
    6.1 - Quality Attributes related to SW release management
    6.2 - Quality Attributes related to SW and services in production

7 - Metadata for software
    7.1 - Metadata schema for SW
    7.2 - The case for FAIR for Research Software (FAIR4RS)
    7.3 - Quality Attributes and the FAIR4RS principles

8 - Summary and conclusions
Appendix - Quality Attributes
References

**Comment by mariojmdavid** [comment]
Agree with section >=3
for section 2 following a suggestion from @mcolom change the section title

2 - Classification of quality characteristics and attributes

**Comment by mcolom** [comment]
Thanks Mario, that's an excellent new title for section 2.

**Comment by mariojmdavid** [comment]
if you agree I will close this issue and update the ToC https://github.com/eosc-sq/ensure-sq/blob/main/docs/toc.md

**Comment by mcolom** [comment]
Ok for me!

**Comment by mariojmdavid** [comment]
solved in git rep and overleaf
