### ISSUE TITLE
For discussion: include section 6 (SW in prod) inside section 4 (recommendations)

### ISSUE THREAD

**Issue by mcolom** [eosc-sq/ensure-sq#35]
Hi all,

I'm opening this for discussion.
Section 6 (SW in production) is very short, and it looks like it could be easily included inside section 4 (recommendations).
The content is good, it's just that it looks like a little disconnected there, and seems to fit well in section 4 as a particular case.

What do you think?

**Comment by mariojmdavid** [comment]
done
