### ISSUE TITLE
Editions to Table 16

### ISSUE THREAD

**Issue by ljgarcia** [eosc-sq/ensure-sq#36]
Please find some suggestions for Table 16. Summary:
* The text in 6.1.1 recognizes multiple approaches for metadata describing software, so should Table 16 --> Codemeta has been replaced for "metadata file" and community standards for software metadata in R3 points back to section 6.1. where some metadata standards are presented.
* Although metadata does support and facilitate FAIRness, on its own is not enough. For instance, some principles rely on community agreements --> community aspect has been added to the text of some of the principles.
* Mention of Software Management Plans was added when referring to elements relevant for the software project.

**Table in HTML**
<table border="1" cellpadding="1" cellspacing="1">
	<tbody>
		<tr>
			<td>FAIR4RS principle</td>
			<td>Quality Attribute</td>
			<td>Rationale</td>
		</tr>
		<tr>
			<td>F1</td>
			<td>EOSC-SWRelMan-11<br />
			EOSC-SWRelMan-13<br />
			EOSC-SWRelMan-25</td>
			<td>A metadata file describing a software component should be appropriately identified and tied to its corresponding software project (e.g., on the source code repository). A software project package should be uploaded to a public registry (e.g., everytime there is a new release). The metadata file should contain the software identifier and its corresponding version Checksums must be used to identify each software binary file uniquely.</td>
		</tr>
		<tr>
			<td>F1.1</td>
			<td>EOSC-SWRelMan-05<br />
			EOSC-SWRelMan-33</td>
			<td>Different branches should be used to address code changes with different scope. Each branch should&nbsp;be identified uniquely within a code repository. The documentation associated to a project must&nbsp;have a persistent identifier and linked to/from the metadata describing the software whenever needed (i.e., if the documentation resides&nbsp; outside the software, each one will have its own persistent identifier).</td>
		</tr>
		<tr>
			<td>F1.2</td>
			<td>EOSC-SWRelMan-02<br />
			EOSC-SWRelMan-04<br />
			EOSC-SWRelMan-06<br />
			EOSC-SWRelMan-09</td>
			<td>A version control system should exist for the software project code, with a main identified branch&nbsp;where new features are merged. A strategy for transitioning between version releases should be in&nbsp;place. Changelogs and/or release notes should be used to keep trace of changes between versions/releases. Semantic versioning should be used to uniquely define each code release.&nbsp;</td>
		</tr>
		<tr>
			<td>F2</td>
			<td>EOSC-SWRelMan-11<br />
			EOSC-SWRelMan-26<br />
			EOSC-SWRelMan-29<br />
			EOSC-SWRelMan-30<br />
			EOSC-SWRelMan-31<br />
			EOSC-SWRelMan-32<br />
			EOSC-Qual-24</td>
			<td>The software project should contain enough information for a reader to verify its objectives. A file including information about the authors (aka creators or contributors) should be provided (e.g., citation file) together with a metadata file&nbsp;describing the software project with links to/from the actual software (be aware that information about the project is not necessarily the same as for the software itself). Software project could benefit from a Software Management Plan. Documentation&nbsp;should be used to describe the Research Software component, using version control to track&nbsp;differences between software versions. A README file should be provided describing the project&nbsp;with metadata in a human-readable format (e.g., installation instructions, authors, citation, etc.).</td>
		</tr>
		<tr>
			<td>F3</td>
			<td>EOSC-SWRelMan-11</td>
			<td>A metadata file should contain an identifier of the software project it describes.</td>
		</tr>
		<tr>
			<td>F4</td>
			<td>EOSC-SWRelMan-11</td>
			<td>A metadata file should be provided to facilitate metadata propagation when releasing code (e.g.&nbsp;storing the code in Zenodo).</td>
		</tr>
		<tr>
			<td>A1</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>A1.1</td>
			<td>EOSC-SWRelMan-01</td>
			<td>The software project should be publicly available online.</td>
		</tr>
		<tr>
			<td>A1.2</td>
			<td>EOSC-SWTest-18</td>
			<td>An authentication mechanism should be enabled for the target service. Metadata describing the software should include, when necessary, information on how to access the software (e.g., membership, payment, free of access) and complemented with a license (discussed later in this table).</td>
		</tr>
		<tr>
			<td>A2</td>
			<td>&nbsp;</td>
			<td>Metadata can be made accessible via registries. It is therefore a good idea to register the software in appropriate registries (e.g., some communities will have their own software registries or will suggest one of general purpose).</td>
		</tr>
		<tr>
			<td>I1</td>
			<td>EOSC-Qual-29<br />
			EOSC-SWTest-01</td>
			<td>The software component should comply with internationally recognized standards. Code should&nbsp;follow standard best practices.</td>
		</tr>
		<tr>
			<td>I2</td>
			<td>&nbsp;</td>
			<td>For instance, software metadata should point to its documentation, tutorials, etc.</td>
		</tr>
		<tr>
			<td>R1</td>
			<td>EOSC-SWRelMan-11<br />
			EOSC-SWRelMan-29</td>
			<td>A metadata file and documentation should describe the software project with accurate, relevant&nbsp;attributes.</td>
		</tr>
		<tr>
			<td>R1.1</td>
			<td>EOSC-SWRelMan-10<br />
			EOSC-SWRelMan-34<br />
			EOSC-SrvOps-01<br />
			EOSC-SrvOps-02</td>
			<td>A license should be associated with the software project, especially if the project is open source.&nbsp;The documentation of a software project should also provide a license. In case a service is deployed,&nbsp;an &ldquo;Acceptable Usage Policy&rdquo; and &ldquo;Terms of Use&rdquo; policy should be clearly defined.</td>
		</tr>
		<tr>
			<td>R1.2</td>
			<td>EOSC-SWRelMan-29<br />
			EOSC-SWRelMan-30</td>
			<td>Software documentation should motivate the rationale and organizations behind the development&nbsp;of a software project, as well as related initiatives that may have been derived from. Funding sources should also be acknowledge.</td>
		</tr>
		<tr>
			<td>R2</td>
			<td>EOSC-SWTest-25<br />
			EOSC-SWRelMan-12</td>
			<td>Third party dependencies should be documented and checked for security flaws. A software project&nbsp;should be adequately packaged and installed, containing all the third party dependencies needed&nbsp;for doing so.</td>
		</tr>
		<tr>
			<td>R3</td>
			<td>EOSC-Qual-29<br />
			EOSC-SWRelMan-32</td>
			<td>A software project should comply with internationally adopted standards. Project documentation&nbsp;should be adapted to the domain-relevant community. Metadata should also comply to community standards(e.g., Codemeta, Bioschemas, see more information in section 6.1).</td>
		</tr>
	</tbody>
</table>

**Table in MD**
| FAIR4RS principle | Quality Attribute | Rationale |
|---|---|---|
| F1 | EOSC-SWRelMan-11 <br/>EOSC-SWRelMan-13 <br/>EOSC-SWRelMan-25 | A metadata file describing a software component should be appropriately identified and tied to its corresponding software project (e.g., on the source code repository). A software project package should be uploaded to a public registry (e.g., everytime there is a new release). The metadata file should contain the software identifier and its corresponding version Checksums must be used to identify each software binary file uniquely. |
| F1.1 | EOSC-SWRelMan-05 <br/>EOSC-SWRelMan-33 | Different branches should be used to address code changes with different scope. Each branch should be identified uniquely within a code repository. The documentation associated to a project must have a persistent identifier and linked to/from the metadata describing the software whenever needed (i.e., if the documentation resides outside the software, each one will have its own persistent identifier). |
| F1.2 | EOSC-SWRelMan-02 <br/>EOSC-SWRelMan-04 <br/>EOSC-SWRelMan-06 <br/>EOSC-SWRelMan-09 | A version control system should exist for the software project code, with a main identified branch where new features are merged. A strategy for transitioning between version releases should be in place. Changelogs and/or release notes should be used to keep trace of changes between versions/releases. Semantic versioning should be used to uniquely define each code release. |
| F2 | EOSC-SWRelMan-11 <br/>EOSC-SWRelMan-26 <br/>EOSC-SWRelMan-29 <br/>EOSC-SWRelMan-30 <br/>EOSC-SWRelMan-31 <br/>EOSC-SWRelMan-32 <br/>EOSC-Qual-24 | The software project should contain enough information for a reader to verify its objectives. A file including information about the authors (aka creators or contributors) should be provided (e.g., citation file) together with a metadata file describing the software project with links to/from the actual software (be aware that information about the project is not necessarily the same as for the software itself). Software project could benefit from a Software Management Plan. Documentation should be used to describe the Research Software component, using version control to track differences between software versions. A README file should be provided describing the project with metadata in a human-readable format (e.g., installation instructions, authors, citation, etc.). |
| F3 | EOSC-SWRelMan-11 | A metadata file should contain an identifier of the software project it describes. |
| F4 | EOSC-SWRelMan-11 | A metadata file should be provided to facilitate metadata propagation when releasing code (e.g storing the code in Zenodo). |
| A1 |   |   |
| A1.1 | EOSC-SWRelMan-01 | The software project should be publicly available online. |
| A1.2 | EOSC-SWTest-18 | An authentication mechanism should be enabled for the target service. Metadata describing the software should include, when necessary, information on how to access the software (e.g., membership, payment, free of access) and complemented with a license (discussed later in this <br/>le). |
| A2 |   | Metadata can be made accessible via registries. It is therefore a good idea to register the software in appropriate registries (e.g., some communities will have their own software registries or will suggest one of general purpose). |
| I1 | EOSC-Qual-29 <br/>EOSC-SWTest-01 | The software component should comply with internationally recognized standards. Code should follow standard best practices. |
| I2 |   | For instance, software metadata should point to its documentation, tutorials, etc. |
| R1 | EOSC-SWRelMan-11 <br/>EOSC-SWRelMan-29 | A metadata file and documentation should describe the software project with accurate, relevant attributes. |
| R1.1 | EOSC-SWRelMan-10 <br/>EOSC-SWRelMan-34 <br/>EOSC-SrvOps-01 <br/>EOSC-SrvOps-02 | A license should be associated with the software project, especially if the project is open source The documentation of a software project should also provide a license. In case a service is deployed, an “Acceptable Usage Policy “and “Terms of Use “policy should be clearly defined. |
| R1.2 | EOSC-SWRelMan-29 <br/>EOSC-SWRelMan-30 | Software documentation should motivate the rationale and organizations behind the development of a software project, as well as related initiatives that may have been derived from. Funding sources should also be acknowledge. |
| R2 | EOSC-SWTest-25 <br/>EOSC-SWRelMan-12 | Third party dependencies should be documented and checked for security flaws. A software project should be adequately packaged and installed, containing all the third-party dependencies needed for doing so. |
| R3 | EOSC-Qual-29 <br/>EOSC-SWRelMan-32 | A software project should comply with internationally adopted standards. Project documentation should be adapted to the domain-relevant community. Metadata should also comply to community standards (e.g., Codemeta, Bioschemas, see more information in section 6.1). |

**Comment by mariojmdavid** [comment]
the final document is almost done, I will implement this for the final version

**Comment by mariojmdavid** [comment]
implemented in master
